const test=require('node:test'),assert=require('node:assert/strict');
const {RemoteControlService}=require('../modules/remote-control');
const {RecoveryController}=require('../modules/recovery-controller');
test('malformed Unicode remote credentials are rejected without throwing',()=>{const s=new RemoteControlService({onAction(){}});s.token='a'.repeat(43);assert.equal(s.tokenMatches('\u00e9'.repeat(43)),false);assert.equal(s.authorized({headers:{authorization:'Bearer '+'\u00e9'.repeat(43)}}),false)});
test('successful load cancels pending recovery reload',()=>{let tasks=new Map(),id=0;const c=new RecoveryController({schedule:f=>{tasks.set(++id,f);return id},cancel:i=>tasks.delete(i)});c.mainFrameFailed(-105);const pending=c.timer;c.loaded();assert.equal(tasks.has(pending),false);c.dispose()});
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../main.js'),'utf8');
function handlerSection(start,end){const i=source.indexOf(start);return source.slice(i,source.indexOf(end,i+start.length))}
test('page sender cannot issue an active-chat send on behalf of another profile',async()=>{let fn;const context={ipcMain:{handle:(c,f)=>fn=f},mainWindow:{webContents:{}},storeUnlocked:true,appLocked:false,activeProfileId:'p',browserViews:{p:{webContents:{getURL:()=> 'https://chat.zalo.me',executeJavaScript:async()=>({ok:true}),insertText(){},focus(){}}}},setTimeout:f=>f()};vm.runInNewContext(handlerSection("  ipcMain.handle('active-chat-send-text'","  ipcMain.handle('zalo-switch-and-send'"),context);assert.equal((await fn({sender:{}},'fixture')).ok,false)});
const rendererSource=fs.readFileSync(path.join(__dirname,'../renderer.js'),'utf8');
test('Pancake detail ignores stale response after a newer selection',async()=>{let pending={};const ctx={pancakeDetailGeneration:0,pancakeRequest:p=>new Promise(r=>pending[p.split('/').pop()]=r),normalizePancakeOrder:x=>x,currentPancakeLink:null,applyPancakeOrder(){},escapeHtml:x=>x,document:{getElementById:()=>({})}};const i=rendererSource.indexOf('async function loadPancakeOrderDetail('),j=rendererSource.indexOf('async function loadPancakeOrders(',i);vm.runInNewContext(rendererSource.slice(i,j),ctx);const a=ctx.loadPancakeOrderDetail('A'),b=ctx.loadPancakeOrderDetail('B');pending.B({order:{orderCode:'B'}});await b;pending.A({order:{orderCode:'A'}});await a;assert.equal(ctx.currentPancakeLink.orderCode,'B')});
test('remote mouse events are ignored while the app is locked',()=>{let fn,calls=0;const window={webContents:{},isDestroyed:()=>false,getContentBounds:()=>({width:1200,height:800})};const ctx={ipcMain:{on:(c,f)=>fn=f},mainWindow:window,appLocked:true,storeUnlocked:true,remoteControl:{getState:()=>({running:true})},normalizeRemoteInput:require('../modules/remote-control').normalizeRemoteInput,activeProfileId:'p',browserViews:{p:{webContents:{isDestroyed:()=>false,sendInputEvent:()=>calls++}}},SIDEBAR_WIDTH:60,TOPBAR_HEIGHT:40};vm.runInNewContext(handlerSection("  ipcMain.on('remote-input-event'","  ipcMain.handle('zalo-group-scan:start'"),ctx);fn({sender:window.webContents},{kind:'mouse',type:'mouseDown',x:.5,y:.5});assert.equal(calls,0)});
test('trusted URL policy rejects lookalike domains, query matches and non-HTTPS',()=>{const ctx={URL};vm.runInNewContext(handlerSection('function isInternalUrl(', 'function getProfilePlatform('),ctx);for(const url of ['https://chat.zalo.me.attacker.invalid/','https://attacker.invalid/?q=chat.zalo.me','file:///chat.zalo.me','javascript:chat.zalo.me'])assert.equal(ctx.isInternalUrl(url),false);assert.equal(ctx.isInternalUrl('https://chat.zalo.me/'),true);assert.equal(ctx.isInternalUrl('https://accounts.google.com/'),true)});
test('remote keyboard targets only the focused active view and respects dock bounds',()=>{let fn;const calls=[];const wc={isDestroyed:()=>false,isFocused:()=>true,insertText:t=>calls.push(t),sendInputEvent(){}};const window={webContents:{},isDestroyed:()=>false,getContentBounds:()=>({width:1200,height:800})};const ctx={ipcMain:{on:(c,f)=>fn=f},mainWindow:window,appLocked:false,storeUnlocked:true,remoteControl:{getState:()=>({running:true})},normalizeRemoteInput:require('../modules/remote-control').normalizeRemoteInput,activeProfileId:'p',browserViews:{p:{webContents:wc,getBounds:()=>({x:60,y:40,width:580,height:760})}},SIDEBAR_WIDTH:60,TOPBAR_HEIGHT:40};vm.runInNewContext(handlerSection("  ipcMain.on('remote-input-event'","  ipcMain.handle('zalo-group-scan:start'"),ctx);fn({sender:window.webContents},{kind:'text',text:'fixture'});assert.equal(calls.length,1);wc.isFocused=()=>false;fn({sender:window.webContents},{kind:'text',text:'blocked'});assert.equal(calls.length,1)});
test('workspace write failure propagates through strict persistence boundary',()=>{const ctx={path,ensureDir(){},isWorkspaceDataFile:()=>false,fs:{writeFileSync(){throw new Error('ENOSPC')}}};vm.runInNewContext(handlerSection('function safeJsonWrite(', 'function normalizeWorkspaceData('),ctx);assert.throws(()=>ctx.safeJsonWrite('fixture.json',{},true),/ENOSPC/)});
test('AI settings no longer copy credentials to plaintext localStorage',()=>{const start=rendererSource.indexOf('function saveAISettings('),end=rendererSource.indexOf('async function runAIRewrite(',start);let saved=false,removed=[];const ctx={workspaceData:{aiSettings:{}},document:{getElementById:()=>({value:'fixture'})},localStorage:{setItem(){throw new Error('plaintext write')},removeItem:k=>{assert.equal(saved,true);removed.push(k)}},persistWorkspace:()=>{saved=true},trackEvent(){}};vm.runInNewContext(rendererSource.slice(start,end),ctx);ctx.saveAISettings();assert.ok(removed.includes('AI_API_KEY'))});
